### ISSUE TITLE
dont start at the paper 1.16.5

### ISSUE THREAD

**Issue by Medved0546** [Maxlego08/zMenu#22]
paper 1.16.5
java 17 temurin from adoptium

[18:48:21] [Server thread/INFO]: [zMenu] Enabling zMenu v1.0.1.8
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] === ENABLE START ===
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Plugin Version V1.0.1.8
[18:48:21] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: zmenu [1.0.1.8]
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Creating default: plugins/zMenu/config.json
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Creating default: plugins/zMenu/players-inventory.json
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] plugins/zMenu/patterns/pattern_example.yml loaded successfully !
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] plugins/zMenu/inventories/advanced_inventory.yml loaded successfully !
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] plugins/zMenu/inventories/basic_inventory.yml loaded successfully !
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] plugins/zMenu/inventories/example_punish.yml loaded successfully !
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] plugins/zMenu/inventories/pro_inventory.yml loaded successfully !
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Command /punish successfully register.
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Command /basic_command successfully register.
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Command /advanced_command successfully register.
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Command /pro_command successfully register.
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Creating default: plugins/zMenu/players.json
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] Scheduler: fr.maxlego08.menu.scheduler.BukkitScheduler@2a8e6425
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] DupeManager: fr.maxlego08.menu.dupe.PDCDupeManager@7154e347
[18:48:21] [Server thread/ERROR]: Error occurred while enabling zMenu v1.0.1.8 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[?:?]
	at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$BuilderImpl.<init>(MiniMessageImpl.java:147) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessage.builder(MiniMessage.java:206) ~[?:?]
	at fr.maxlego08.menu.zcore.utils.meta.ComponentMeta.<init>(ComponentMeta.java:33) ~[?:?]
	at fr.maxlego08.menu.zcore.utils.meta.Meta.<clinit>(Meta.java:19) ~[?:?]
	at fr.maxlego08.menu.zcore.ZPlugin.postEnable(ZPlugin.java:75) ~[?:?]
	at fr.maxlego08.menu.MenuPlugin.onEnable(MenuPlugin.java:218) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[18:48:21] [Server thread/INFO]: [zMenu] Disabling zMenu v1.0.1.8
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] === DISABLE START ===
[18:48:21] [Server thread/INFO]: [zMenu v1.0.1.8] === DISABLE DONE (1ms) ===

**Comment by Medved0546** [comment]
> Owner

its help me thanks
