### ISSUE TITLE
Folia loading problem

### ISSUE THREAD

**Issue by MrSugar08** [Maxlego08/zMenu#35]
This server is running Folia version git-Folia-"1e5e215" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1e5e215

[01:16:03 INFO]: [zMenu] Enabling zMenu v1.0.2.3
[01:16:03 INFO]: [zMenu v1.0.2.3] === ENABLE START ===
[01:16:03 INFO]: [zMenu v1.0.2.3] Plugin Version V1.0.2.3
[01:16:03 INFO]: [PlaceholderAPI] Successfully registered internal expansion: zmenu [1.0.2.3]
[01:16:03 INFO]: [zMenu v1.0.2.3] plugins/zMenu/patterns/pattern_example.yml loaded successfully !
[01:16:03 INFO]: [zMenu v1.0.2.3] plugins/zMenu/inventories/basic_inventory.yml loaded successfully !
[01:16:03 INFO]: [zMenu v1.0.2.3] plugins/zMenu/inventories/advanced_inventory.yml loaded successfully !
[01:16:03 INFO]: [zMenu v1.0.2.3] plugins/zMenu/inventories/pro_inventory.yml loaded successfully !
[01:16:03 INFO]: [zMenu v1.0.2.3] plugins/zMenu/inventories/example_punish.yml loaded successfully !
[01:16:03 INFO]: [zMenu v1.0.2.3] Command /basic_command successfully register.
[01:16:03 INFO]: [zMenu v1.0.2.3] Command /advanced_command successfully register.
[01:16:03 INFO]: [zMenu v1.0.2.3] Command /pro_command successfully register.
[01:16:03 INFO]: [zMenu v1.0.2.3] Command /punish successfully register.
[01:16:03 ERROR]: Error occurred while enabling zMenu v1.0.2.3 (Is it up to date?)
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:257) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at fr.maxlego08.menu.zcore.utils.plugins.VersionChecker.getVersion(VersionChecker.java:91) ~[zMenu.jar:?]
	at fr.maxlego08.menu.zcore.utils.plugins.VersionChecker.useLastVersion(VersionChecker.java:53) ~[zMenu.jar:?]
	at fr.maxlego08.menu.MenuPlugin.onEnable(MenuPlugin.java:205) ~[zMenu.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:16:03 INFO]: [zMenu] Disabling zMenu v1.0.2.3
[01:16:03 INFO]: [zMenu v1.0.2.3] === DISABLE START ===
[01:16:03 INFO]: [zMenu v1.0.2.3] === DISABLE DONE (24ms) ===

**Comment by Maxlego08** [comment]
Fixed for the next version
