### ISSUE TITLE
Many functions do not work for Folia

### ISSUE THREAD

**Issue by Potenza7** [Maxlego08/zMenu#63]
I can see the menu but the some functions do not work.  It does not perform its functions. For example, it does not send commands to the console. Menus open, but most of the command functions cannot be performed. It just does simple functions like back and forth. As an example, I purchased the home config, but this is the error I encounter in the console when I press the buttons on the gui screen.

[12:52:36 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1031) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at fr.maxlego08.menu.button.ZPerformButton.lambda$execute$1(ZPerformButton.java:130) ~[zmenu-1.0.2.9.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at fr.maxlego08.menu.button.ZPerformButton.execute(ZPerformButton.java:123) ~[zmenu-1.0.2.9.jar:?]
        at fr.maxlego08.menu.button.ZPerformButton.lambda$execute$0(ZPerformButton.java:106) ~[zmenu-1.0.2.9.jar:?]
        at fr.maxlego08.menu.zcore.utils.folialib.impl.FoliaImplementation.lambda$runNextTick$0(FoliaImplementation.java:36) ~[zmenu-1.0.2.9.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:52:36 WARN]: java.lang.IllegalStateException: Dispatching command async
[12:52:36 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79)
[12:52:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1031)
[12:52:36 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094)
[12:52:36 WARN]:        at zmenu-1.0.2.9.jar//fr.maxlego08.menu.button.ZPerformButton.lambda$execute$1(ZPerformButton.java:130)
[12:52:36 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[12:52:36 WARN]:        at zmenu-1.0.2.9.jar//fr.maxlego08.menu.button.ZPerformButton.execute(ZPerformButton.java:123)
[12:52:36 WARN]:        at zmenu-1.0.2.9.jar//fr.maxlego08.menu.button.ZPerformButton.lambda$execute$0(ZPerformButton.java:106)
[12:52:36 WARN]:        at zmenu-1.0.2.9.jar//fr.maxlego08.menu.zcore.utils.folialib.impl.FoliaImplementation.lambda$runNextTick$0(FoliaImplementation.java:36)
[12:52:36 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47)
[12:52:36 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179)
[12:52:36 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
[12:52:36 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293)
[12:52:36 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148)
[12:52:36 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[12:52:36 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[12:52:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Maxlego08** [comment]
Hello, do you have more information to provide? Give me the version of your server, the version of folia and the version of the plugin. I would also like to get the configuration you are using.

**Comment by Melon-Oof** [comment]
folia-1.20.4.jar:git-Folia-"e97b1ee"
zmenu-1.0.2.9

I'm not associated with the user "Potenza7" just saw the post on [discord](https://discord.com/channels/511516467615760405/1225760434611552289/1225760434611552289) and wanted to help so here's the info you requested, and the following user claimed to have purchased the [home config](https://minecraft-inventory-builder.com/resources/donutsmp-home-zmenu-configurations.7) <-- I believe this one as is the only one I've seen on the website.

**Comment by Maxlego08** [comment]
> folia-1.20.4.jar:git-Folia-"e97b1ee" zmenu-1.0.2.9
> 
> I'm not associated with the user "Potenza7" just saw the post on [discord](https://discord.com/channels/511516467615760405/1225760434611552289/1225760434611552289) and wanted to help so here's the info you requested, and the following user claimed to have purchased the [home config](https://minecraft-inventory-builder.com/resources/donutsmp-home-zmenu-configurations.7) <-- I believe this one as is the only one I've seen on the website.
> 
> I've gathered the information about the server's version and plugin version thru the mclo.gs the user sent on the discord thread, https://mclo.gs/OCEWg5U

Plz join idscord for support, create a post on #zmenus

**Comment by Melon-Oof** [comment]
Can I ping you in his post?

**Comment by Maxlego08** [comment]
yes
