### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 404forever1** [Maxlego08/zMenu#72]
[22:22:28 ERROR]: Could not pass event InventoryClickEvent to zMenu v1.0.3.0
java.lang.IllegalStateException: Dispatching command async
        at io.papermc.paper.threadedregions.RegionizedServer.ensureGlobalTickThread(RegionizedServer.java:105) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1036) ~[luminol-1.20.4.jar:git-Luminol-"01a
bc6c"]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at fr.maxlego08.menu.requirement.actions.ConsoleCommandAction.lambda$execute$0(ConsoleCommandAction.java:23) ~[zmenu-1.0.3.
0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at fr.maxlego08.menu.requirement.actions.ConsoleCommandAction.execute(ConsoleCommandAction.java:22) ~[zmenu-1.0.3.0.jar:?]
        at fr.maxlego08.menu.api.requirement.Action.preExecute(Action.java:25) ~[zmenu-1.0.3.0.jar:?]
        at fr.maxlego08.menu.button.ZButton.lambda$onClick$2(ZButton.java:241) ~[zmenu-1.0.3.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at fr.maxlego08.menu.button.ZButton.onClick(ZButton.java:241) ~[zmenu-1.0.3.0.jar:?]
        at fr.maxlego08.menu.inventory.inventories.InventoryDefault.lambda$displayFinalButton$5(InventoryDefault.java:194) ~[zmenu-
1.0.3.0.jar:?]
        at fr.maxlego08.menu.zcore.utils.inventory.ItemButton.onClick(ItemButton.java:66) ~[zmenu-1.0.3.0.jar:?]
        at fr.maxlego08.menu.inventory.VInventoryManager.onInventoryClick(VInventoryManager.java:149) ~[zmenu-1.0.3.0.jar:?]
        at fr.maxlego08.menu.listener.AdapterListener.lambda$onInventoryClick$2(AdapterListener.java:53) ~[zmenu-1.0.3.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at fr.maxlego08.menu.listener.AdapterListener.onInventoryClick(AdapterListener.java:53) ~[zmenu-1.0.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor466.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"01abc
6c"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"
]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Lumino
l-"01abc6c"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3197) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"
]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.20.4.jar:git-L
uminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Maxlego08** [comment]
Hey, this bug is already fix, use that: https://cdn.discordapp.com/attachments/688730543977660495/1236687837139701770/zmenu-1.0.3.0.jar?ex=6638eacc&is=6637994c&hm=17370299c7479a7ec9bd1a7a529e72726648576cee8ad0700b9aa4d95ef33f3e&
