### ISSUE TITLE
Issues with zMenu v1.0.3.1 

### ISSUE THREAD

**Issue by IsmaelTechDEV** [Maxlego08/zMenu#78]
###The error is:
[00:48:35 INFO]: ------------------------------------
[00:48:35 INFO]: [zMenu] Enabling zMenu v1.0.3.1
[00:48:35 INFO]: [zMenu v1.0.3.1] === ENABLE START ===
[00:48:35 INFO]: [zMenu v1.0.3.1] Plugin Version V1.0.3.1
[00:48:35 INFO]: [PlaceholderAPI] Successfully registered internal expansion: zmenu [1.0.3.1]
[00:48:35 INFO]: [zMenu v1.0.3.1] Creating default: plugins/zMenu/config.json
[00:48:35 INFO]: [zMenu v1.0.3.1] Creating default: plugins/zMenu/players-inventory.json
[00:48:36 INFO]: [zMenu v1.0.3.1] plugins/zMenu/patterns/pattern_example.yml loaded successfully !
[00:48:36 INFO]: [zMenu v1.0.3.1] plugins/zMenu/inventories/basic_inventory.yml loaded successfully !
[00:48:36 INFO]: [zMenu v1.0.3.1] plugins/zMenu/inventories/pro_inventory.yml loaded successfully !
[00:48:36 INFO]: [zMenu v1.0.3.1] plugins/zMenu/inventories/example_punish.yml loaded successfully !
[00:48:36 INFO]: [zMenu v1.0.3.1] plugins/zMenu/inventories/advanced_inventory.yml loaded successfully !
[00:48:36 INFO]: [zMenu v1.0.3.1] plugins/zMenu/website/inventories.yml loaded successfully !
[00:48:36 INFO]: [zMenu v1.0.3.1] Command /basic_command successfully register.
[00:48:36 INFO]: [zMenu v1.0.3.1] Command /advanced_command successfully register.
[00:48:36 INFO]: [zMenu v1.0.3.1] Command /pro_command successfully register.
[00:48:36 INFO]: [zMenu v1.0.3.1] Unable to add the command /openbook
[00:48:36 INFO]: [zMenu v1.0.3.1] Command /openbook successfully register.
[00:48:36 INFO]: [zMenu v1.0.3.1] Command /punish successfully register.
[00:48:36 INFO]: [zMenu v1.0.3.1] Creating default: plugins/zMenu/players.json
[00:48:36 INFO]: [zMenu v1.0.3.1] 
[00:48:36 INFO]: [zMenu v1.0.3.1] You can support zMenu by upgrading your account here: https://minecraft-inventory-builder.com/account-upgrade
[00:48:36 INFO]: [zMenu v1.0.3.1] zMenu’s site includes an inventory editor (under development), a marketplace (already available) is a forum (under development)
[00:48:36 INFO]: [zMenu v1.0.3.1] 
[00:48:36 ERROR]: Error occurred while enabling zMenu v1.0.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/tag/resolver/TagResolver
	at fr.maxlego08.menu.zcore.utils.meta.ComponentMeta.<init>(ComponentMeta.java:36) ~[zmenu-1.0.3.1-1.0.3.1.jar:?]
	at fr.maxlego08.menu.zcore.utils.meta.Meta.<clinit>(Meta.java:19) ~[zmenu-1.0.3.1-1.0.3.1.jar:?]
	at fr.maxlego08.menu.zcore.ZPlugin.postEnable(ZPlugin.java:75) ~[zmenu-1.0.3.1-1.0.3.1.jar:?]
	at fr.maxlego08.menu.MenuPlugin.onEnable(MenuPlugin.java:243) ~[zmenu-1.0.3.1-1.0.3.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.tag.resolver.TagResolver
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 14 more
[00:48:36 INFO]: [zMenu] Disabling zMenu v1.0.3.1
[00:48:36 INFO]: [zMenu v1.0.3.1] === DISABLE START ===
[00:48:36 INFO]: [zMenu v1.0.3.1] === DISABLE DONE (2ms) ===

[00:51:37 INFO]: Plugins (42): AdvancedCrates, ajLeaderboards, AuctionHouse, AuraSkills, BetterRTP, BlockParticles, Citizens, CMI, CMILib, ConsumeFood, DailyRewardsPlus, DecentHolograms, DeluxeCombat, DeluxeMenus, EasyCommandBlocker, EvenMoreFish, GriefDefender, Guilds, Infiniteannouncements, Jobs, LuckPerms, MTBackpack, NBTAPI, PlaceholderAPI, PlayerKits, ProtocolLib, Quests, ShopGUIPlus, SilkSpawners_v2, SimpleScore, TAB, TradeMe, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags, zMenu

[00:51:43 INFO]: This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

**Comment by Maxlego08** [comment]
Disable mini message format
